### ISSUE TITLE
Video doesn't play from the HA lovelace UI

### ISSUE THREAD

**Issue by mahoekst** [jeroenterheerdt/ring-hassio#4]
Addon is running. Opening the URL in VLC shows the video stream. But when clicking on the camera in the UI it keeps showing the spinning wheel.

When inspecting the HTML this is the video part:
<video autoplay="" muted="" playsinline="" controls="" src="blob:http://hassio.local:8123/571d3ce0-267d-4c73-bf05-7468b5789563"></video>

When I open the http piece in the browser I get a 404 not found error

This is the entry in my configuration.yaml

    
camera:
  - platform: generic
    name: Ring Livestream
    stream_source: http://hassio.local:3000/public/stream.m3u8
    still_image_url: http://hassio.local:3000/public/stream.m3u8

**Comment by jeroenterheerdt** [comment]
No idea, if the stream works in VLC then it should work in Lovelace UI you configure it correctly.

**Comment by jeroenterheerdt** [comment]
I have looked into this further - it seems that the `stream` component is required as well. Like this (no futher config on `stream` required):
```
stream:
camera:
  - platform: generic
    name: Ring Livestream
    stream_source: http://hassio.local:port/public/stream.m3u8
    still_image_url: http://hassio.local:port/public/stream.m3u8
```
