### ISSUE TITLE
Battery Conservation

### ISSUE THREAD

**Issue by Harryjholmes** [jeroenterheerdt/ring-hassio#6]
This add on is great by the way. I can access ring doorbell streams successfully. I am trying to conserve the battery of the doorbell and the connection doesn't seem to close when home assistant stops viewing the stream. Looking at the logs the stream numbers just keeps increasing. Is there anyway to stop streaming and reopen upon new connection.

Thanks in Advance
@jeroenterheerdt

**Comment by jeroenterheerdt** [comment]
yep, I know that battery usage is an issue. I have not found a way to start/stop the stream when HA is looking at it or not. So maybe it would be better to run your Ring on wired power if you can? :)

**Comment by Harryjholmes** [comment]
Yeah I have got it powered but obviously not sufficiently as it drained my doorbell 2 completely overnight. Is there no way to allow, for example, a 30 second stream and then wait for a new connection? @jeroenterheerdt

**Comment by Harryjholmes** [comment]
@jeroenterheerdt The ring-homebrige integration doesn't drain battery so it must be possible?

**Comment by jeroenterheerdt** [comment]
the thing is that I have not found a way to activate the livestream on-demand.

**Comment by Harryjholmes** [comment]
This looks useful

**Comment by jeroenterheerdt** [comment]
Yeah it does, problem is that I don't know how HA can tell us that we need a livestream. Something like the UI saying the ring card is in view or out of view would be useful

**Comment by Harryjholmes** [comment]
I see what you mean. Surely when you open the stream on HA that’s when it uses the url to get a stream. I’m not sure it constantly streams all the time.

**Comment by jeroenterheerdt** [comment]
right, but how do we know HA does not need the stream any longer...? I am not seeing anything that I can use for example on the frontend to query if the stream is in view. To be fair, I have not looked into it that much.

**Comment by Harryjholmes** [comment]
Would HA reconnect if you ended the stream every 30seconds or so until new connection?

**Comment by luci-11** [comment]
Hi, 
I'm using nginx too. I use the addon by Frenck: [Nginx Proxy Manager](https://github.com/hassio-addons/addon-nginx-proxy-manager)
I tested this 3 methods:
With local ip:
```
sensor:
  - platform: rest
    resource: "http://hassio_ip:8123/api/hassio/addons/xxxxxxxx_ringlivestream/info"
    headers:
      Authorization: "Bearer [Long_lived_token]"
      Content-Type: application/json
    name: ring_addon_official_online
    value_template: "{{value_json['data']['state']}}"
```

With domain:
```
sensor:
  - platform: rest
    resource: "https://yoursite.yourdomain.org/api/hassio/addons/xxxxxxxx_ringlivestream/info"
    headers:
      Authorization: "Bearer [Long_lived_token]"
      Content-Type: application/json
    name: ring_addon_official_online
    value_template: "{{value_json['data']['state']}}"
```

Or you can try the method below. It takes a couple of seconds to update after reboot  and the sensor should be updated manually after start/stop command to the addon (so the switch is replaced by two scripts) :

```
sensor:
  - platform: command_line
    name: Supervisor_2
    command: 'curl https://yoursite.yourdomain.org/api/hassio/supervisor/info -H "Authorization: Bearer [Long_lived_token]" | jq ''{"state":.data.state,"slug":.data.slug,"addons":[.data.addons[] | select(.slug == "XXXXXXXX_ringlivestream")]}'''
    value_template: "{{ value_json.addons | length }}"
    json_attributes:
      - addons

  - platform: template
    sensors:
      ring_addon_status_from_command_line:
        friendly_name: "Ring"
        value_template: >-
          {{ state_attr('sensor.supervisor_2', 'addons')|regex_findall_index(".state'...(.+)', 'version'") }}

script:
  ring_start:
    sequence:
      - service: hassio.addon_start
        data:
          addon: XXXXXXXX_ringlivestream
      - service: shell_command.check_status
  ring_stop:
    sequence:
      - service: hassio.addon_stop
        data:
          addon: XXXXXXXX_ringlivestream
      - service: shell_command.check_status

shell_command:
  check_status: 'curl https://yoursite.yourdomain.org/api/hassio/supervisor/info -H "Authorization: Bearer [Long_Lived_Token]"'
 
```
This sensor is updated slower than the two above.

I'll do the PR for the .js part in some minutes.
I wanted also to tell you that in my case the stream works also without opening the port on router.

**Comment by jeroenterheerdt** [comment]
I used the `NGINX Home Assistant TSL Proxy`, will check with the proxy manager to see if that changes anything. thanks.

**Comment by jeroenterheerdt** [comment]
well, that was quick - the Proxy Manager does not even start, no logging, nothing. Hmpf.

**Comment by angadsingh** [comment]
@jeroenterheerdt great work man! please make this more stable and add on-demand starting/stopping of the RTSP server based on access. I created the template switch and sensor as suggested here and went ahead and created a script as well which will start the addon, cast the camera to my nest hub display, wait 1.5 minutes, stop the cast, and then finally stop the addon:

```
cast_ring_doorbell_to_nest_display:
  alias: Cast ring doorbell to nest display
  sequence:
  - data: {}
    entity_id: switch.ring_live_stream_addon_switch
    service: switch.turn_on
  - condition: state
    entity_id: switch.ring_live_stream_addon_switch
    state: 'on'
  - data:
      media_player: media_player.living_room_display
    entity_id: camera.ring_livestream
    service: camera.play_stream
  - delay: 00:01:30
  - data: {}
    entity_id: media_player.living_room_display
    service: media_player.media_stop
  - data: {}
    entity_id: switch.ring_live_stream_addon_switch
    service: switch.turn_off
```

however this was a big failure. it would take forever for the addon to achieve the on state, and then it would take forever for the cast to start streaming after initially showing up. if the addon itself killed its upstream link to the camera for battery preservation that would be much much faster. here's how the battery dies when using this addon:
![B8AC1CC5-73CD-423D-9BF9-805617E98B31](https://user-images.githubusercontent.com/1623026/88136853-d6df0980-cc07-11ea-9cb0-92b3951aa8f1.jpg)

notice the times when the addon was running its almost like a flat line. drains maybe 2% per day. with the addon running its almost 1% every 5 minutes. the only way to use this addon in its current state would be to have a wired power connection to the doorbell.
